const categores = [
  {
    name: 'парикмахерские услуги',
    available: true,
    index: 1,
  },
  { name: 'маникюр', available: true, index: 2 },
  { name: 'педикюр', available: true, index: 3 },
  {
    name: 'брови и ресницы',
    available: true,
    index: 4,
  },
];

const subCategores = [
  {
    name: 'стрижка',
    categoryId: 'AdnebHuBf0PKxsddSCcm',
    index: 1,
  },
  {
    name: 'укладка',
    categoryId: 'AdnebHuBf0PKxsddSCcm',
    index: 2,
  },
  {
    name: 'окрашивание',
    categoryId: 'AdnebHuBf0PKxsddSCcm',
    index: 3,
  },
  {
    name: 'долговременная укладка',
    categoryId: 'AdnebHuBf0PKxsddSCcm',
    index: 4,
  },
  {
    name: 'уход',
    categoryId: 'AdnebHuBf0PKxsddSCcm',
    index: 5,
  },
];

const services = [
  {
    name: 'Стрижка женская',
    categoryId: 'AdnebHuBf0PKxsddSCcm',
    subCategoryId: 'KPnRICkIe2KbpvZdQWvV',
    price: '800/1000/1200',
    duration: [2, 3, 3],
    index: 1,
  },
  {
    name: 'Стрижка мужская',
    categoryId: 'AdnebHuBf0PKxsddSCcm',
    subCategoryId: 'KPnRICkIe2KbpvZdQWvV',
    price: '400/600/800',
    duration: [2],
    index: 2,
  },
  {
    name: 'Укладка повседневная',
    categoryId: 'AdnebHuBf0PKxsddSCcm',
    subCategoryId: 'LLqxMsFN02cvHPtl00Jx',
    price: '600/800/1000',
    duration: [2, 2, 3],
    index: 1,
  },
  {
    name: 'Укладка локоны',
    categoryId: 'AdnebHuBf0PKxsddSCcm',
    subCategoryId: 'LLqxMsFN02cvHPtl00Jx',
    price: '1500/2500',
    duration: [4, 4, 5],
    index: 2,
  },
  {
    name: 'Окрашивание в один тон/тонирование',
    categoryId: 'AdnebHuBf0PKxsddSCcm',
    subCategoryId: 'EE18oQDcStzC4kzQ5Jkp',
    price: '2000/2500/3000',
    duration: [4, 5, 6],
    index: 1,
  },
  {
    name: 'Окрашивание корней',
    categoryId: 'AdnebHuBf0PKxsddSCcm',
    subCategoryId: 'EE18oQDcStzC4kzQ5Jkp',
    price: '1500/1800/2300',
    duration: [4, 4, 5],
    index: 2,
  },
  {
    name: 'Мелирование',
    categoryId: 'AdnebHuBf0PKxsddSCcm',
    subCategoryId: 'EE18oQDcStzC4kzQ5Jkp',
    price: '2000/2500/3000',
    duration: [5, 6, 7],
    index: 3,
  },
  {
    name: 'Колорирование',
    categoryId: 'AdnebHuBf0PKxsddSCcm',
    subCategoryId: 'EE18oQDcStzC4kzQ5Jkp',
    price: '2500/3000/3500',
    duration: [5, 6, 8],
    index: 4,
  },
  {
    name: 'Сложное окрашивание',
    categoryId: 'AdnebHuBf0PKxsddSCcm',
    subCategoryId: 'EE18oQDcStzC4kzQ5Jkp',
    price: '4000/6000',
    duration: [6, 6, 10],
    index: 5,
  },
  {
    name: 'Декапирование',
    categoryId: 'AdnebHuBf0PKxsddSCcm',
    subCategoryId: 'EE18oQDcStzC4kzQ5Jkp',
    price: '1000/1500/2000',
    duration: [4, 5, 6],
    index: 6,
  },
  {
    name: 'Химическая завивка',
    categoryId: 'AdnebHuBf0PKxsddSCcm',
    subCategoryId: 'k4n1v5gRar611iBOt0r6',
    price: '2000/3000/4000',
    duration: [5, 6, 8],
    index: 1,
  },
  {
    name: 'Биозавивка',
    categoryId: 'AdnebHuBf0PKxsddSCcm',
    subCategoryId: 'k4n1v5gRar611iBOt0r6',
    price: '2500/3500/4500',
    duration: [5, 6, 8],
    index: 2,
  },
  {
    name: 'Ламинирование',
    categoryId: 'AdnebHuBf0PKxsddSCcm',
    subCategoryId: 'kTkLxmpyGVW7ZGv3jpJF',
    price: '500/1000/1500',
    duration: [3, 4, 5],
    index: 1,
  },
  {
    name: 'Ботокс',
    categoryId: 'AdnebHuBf0PKxsddSCcm',
    subCategoryId: 'kTkLxmpyGVW7ZGv3jpJF',
    price: '2000/3000/4000',
    duration: [4, 6, 8],
    index: 2,
  },
  {
    name: 'Нанопластика',
    categoryId: 'AdnebHuBf0PKxsddSCcm',
    subCategoryId: 'kTkLxmpyGVW7ZGv3jpJF',
    price: '3000/4000',
    duration: [6, 6, 8],
    index: 3,
  },
  {
    name: 'Кератиновое выпрямление',
    categoryId: 'AdnebHuBf0PKxsddSCcm',
    subCategoryId: 'kTkLxmpyGVW7ZGv3jpJF',
    price: '4000/5000',
    duration: [8, 8, 10],
    index: 4,
  },
  {
    name: 'Женский',
    categoryId: 'Vsp9niZdfqhQAEx1K6mf',
    subCategoryId: null,
    price: '700',
    duration: [3],
    index: 1,
  },
  {
    name: 'Мужской',
    categoryId: 'Vsp9niZdfqhQAEx1K6mf',
    subCategoryId: null,
    price: '900',
    duration: [3],
    index: 2,
  },
  {
    name: 'Снятие гель-лака',
    categoryId: 'Vsp9niZdfqhQAEx1K6mf',
    subCategoryId: null,
    price: '300',
    duration: [1],
    index: 3,
  },
  {
    name: 'Выравнивание',
    categoryId: 'Vsp9niZdfqhQAEx1K6mf',
    subCategoryId: null,
    price: '200',
    duration: [],
    index: 4,
  },
  {
    name: 'Наращивание ногтей',
    categoryId: 'Vsp9niZdfqhQAEx1K6mf',
    subCategoryId: null,
    price: '2200',
    duration: [7],
    index: 5,
  },
  {
    name: 'Снятие нарощенных ногтей',
    categoryId: 'Vsp9niZdfqhQAEx1K6mf',
    subCategoryId: null,
    price: '400',
    duration: [2],
    index: 6,
  },
  {
    name: 'Френч',
    categoryId: 'Vsp9niZdfqhQAEx1K6mf',
    subCategoryId: null,
    price: '400',
    duration: [1],
    index: 7,
  },
  {
    name: 'Дизайн 1 ногтя',
    categoryId: 'Vsp9niZdfqhQAEx1K6mf',
    subCategoryId: null,
    price: '50-200',
    duration: [],
    index: 8,
  },
  {
    name: 'Ремонт 1 ногтя',
    categoryId: 'Vsp9niZdfqhQAEx1K6mf',
    subCategoryId: null,
    price: '50-200',
    duration: [],
    index: 9,
  },
  {
    name: 'Комплекс (снятие + маникюр + выравнивание + покрытие гель-лак)',
    categoryId: 'Vsp9niZdfqhQAEx1K6mf',
    subCategoryId: null,
    price: '1600',
    duration: [6],
    index: 10,
  },
  {
    name: 'Аппаратный педикюр',
    categoryId: 'U9qCJM8HJ1B4yZ74Qai7',
    subCategoryId: null,
    price: '1200',
    duration: [3],
    index: 1,
  },
  {
    name: 'SMART педикюр',
    categoryId: 'U9qCJM8HJ1B4yZ74Qai7',
    subCategoryId: null,
    price: '1500',
    duration: [3],
    index: 2,
  },
  {
    name: 'Обработка пальчиков',
    categoryId: 'U9qCJM8HJ1B4yZ74Qai7',
    subCategoryId: null,
    price: '800',
    duration: [2],
    index: 3,
  },
  {
    name: 'Комплекс(снятие + аппаратный педикюр с обработкой стоп + покрытие)',
    categoryId: 'U9qCJM8HJ1B4yZ74Qai7',
    subCategoryId: null,
    price: '2000',
    duration: [4],
    index: 4,
  },
  {
    name: 'Комплекс(снятие + SMART-педикюр с обработкой стоп + покрытие)',
    categoryId: 'U9qCJM8HJ1B4yZ74Qai7',
    subCategoryId: null,
    price: '2300',
    duration: [4],
    index: 5,
  },
  {
    name: 'Коррекция формы',
    categoryId: 'HRpwRehNgnrMA6cLQqpg',
    subCategoryId: null,
    price: '400',
    duration: [],
    index: 1,
  },
  {
    name: 'Окрашивание бровей',
    categoryId: 'HRpwRehNgnrMA6cLQqpg',
    subCategoryId: null,
    price: '600',
    duration: [],
    index: 2,
  },
  {
    name: 'Архитектура бровей',
    categoryId: 'HRpwRehNgnrMA6cLQqpg',
    subCategoryId: null,
    price: '1200',
    duration: [],
    index: 3,
  },
  {
    name: 'Ламинирование бровей',
    categoryId: 'HRpwRehNgnrMA6cLQqpg',
    subCategoryId: null,
    price: '700',
    duration: [],
    index: 4,
  },
  {
    name: 'Окрашивание ресниц',
    categoryId: 'HRpwRehNgnrMA6cLQqpg',
    subCategoryId: null,
    price: '500',
    duration: [],
    index: 5,
  },
  {
    name: 'Комплексдля бровей(коррекция + окрашивание + ламинирование + ботокс в подарок)',
    categoryId: 'HRpwRehNgnrMA6cLQqpg',
    subCategoryId: null,
    price: '1500',
    duration: [],
    index: 6,
  },
  {
    name: 'Комплекс для ресниц(окрашивание + ламинирование + ботокс в подарок)',
    categoryId: 'HRpwRehNgnrMA6cLQqpg',
    subCategoryId: null,
    price: '1500',
    duration: [],
    index: 7,
  },
];

const masters = [
  {
    name: 'Ульяна',
    categoryIdList: [
      'AdnebHuBf0PKxsddSCcm',
      'Vsp9niZdfqhQAEx1K6mf',
    ],
    weekends: [],
    disabledDates: [],
    available: true,
    index: 1,
  },
  {
    name: 'Светлана',
    categoryIdList: ['AdnebHuBf0PKxsddSCcm'],
    weekends: [],
    disabledDates: [],
    available: true,
    index: 2,
  },
  {
    name: 'Катя',
    categoryIdList: [
      'Vsp9niZdfqhQAEx1K6mf',
      'U9qCJM8HJ1B4yZ74Qai7',
    ],
    weekends: [],
    disabledDates: [],
    available: false,
    index: 3,
  },
  {
    name: 'Маша',
    categoryIdList: ['HRpwRehNgnrMA6cLQqpg'],
    weekends: [],
    disabledDates: [],
    available: true,
    index: 4,
  },
];

export {
  categores,
  subCategores,
  services,
  masters,
};
